### ISSUE TITLE
Undeploys of Shared Flows fails with 415

### ISSUE THREAD

**Issue by mikeleaver** [apigee/apigee-deploy-maven-plugin#81] opened 2017-09-21 03:21 UTC
Undeploys of Shared Flows are failing with 415 error due to Content-Type: application/x-www-form-urlencoded header

**Comment by ssvaidyanathan** [comment] 2017-10-24 18:51
Isnt this the duplicate of https://github.com/apigee/apigee-deploy-maven-plugin/pull/80 ?

**Comment by mikeleaver** [comment] 2017-10-26 04:47
Yes. #80 is the pull request

**Comment by ssvaidyanathan** [comment] 2017-10-26 15:58
I am closing this issue as the PR is complete.. We are reviewing other issues before we do a release

**Closed by ssvaidyanathan** 2017-10-26 15:58 UTC

**Comment by ssvaidyanathan** [comment] 2017-12-23 04:38
Released in v1.1.6
For more info:
https://github.com/apigee/apigee-deploy-maven-plugin/releases/tag/apigee-edge-maven-plugin-1.1.6
