### ISSUE TITLE
shared flow deploy question

### ISSUE THREAD

**Issue by seantdg** [apigee/apigee-deploy-maven-plugin#90] opened 2018-02-16 12:52 UTC
when we deploy a shared flow, does it also deploy a proxy with the same name? what might be the reason for this?

Thanks in advance @ssvaidyanathan !

**Comment by kurtkanaskie** [comment] 2018-02-27 22:41
I think this is a bug, community article here: https://community.apigee.com/questions/53787/shared-flows-appear-in-api-proxies-list-in-edge-ui.html
I saw this once but could not reproduce.

**Comment by ssvaidyanathan** [comment] 2018-03-30 20:37
I dont think the plugin is doing it unless you have an execution within the pom that does it. There have been some posts in the community that they can see shared flow within the API Proxies list page. Not sure if its the deploy plugin that is doing this. Probably Mgmt UI thing

**Comment by ssvaidyanathan** [comment] 2019-12-27 18:52
Closing this as its not plugin related

**Closed by ssvaidyanathan** 2019-12-27 18:52 UTC
