### ISSUE TITLE
Bundle activation issue for 1.x version if deployment takes more than 10 seconds

### ISSUE THREAD

**Issue by vctrainings08** [apigee/apigee-deploy-maven-plugin#213] opened 2023-05-30 07:19 UTC
Hi Team,

Getting bundle activation issues if deployment takes more than 10 seconds and I found that sleep time is harcoded. Is there any way we can make it parameterized. 

Code snippet is below from RestClient.java from 1.3.3.

if (this.getProfile().isOverride()) {
                for (final BundleActivationConfig config : deployment3.environment) {
                    if (config.environment.equalsIgnoreCase(this.profile.getEnvironment())) {
                        if (!config.state.equalsIgnoreCase("deployed")) {
                            RestClient.log.info("Waiting to assert bundle activation.....");
                            **Thread.sleep(10L);**
                            final Long deployedRevision = this.getDeployedRevision(bundle);
                            if (bundle.getRevision() != null && bundle.getRevision().equals(deployedRevision)) {
                                RestClient.log.info("Deployed revision is: " + bundle.getRevision());
                                return "deployed";
                            }
                            RestClient.log.error("Deployment failed to activate");
                            throw new MojoExecutionException("Deployment failed: Bundle did not activate within expected time. Please check deployment status manually before trying again");
                        }
                        else {
                            RestClient.log.info(PrintUtil.formatResponse(response, this.gson.toJson((Object)deployment3)));
                        }
                    }
                }
            }

**Comment by vctrainings08** [comment] 2023-05-31 17:09
I'm already using option as override with apigee.override.delay configured, but apigee.delay is commented though. Is apigee.delay required for proxy update with override (seamless deployment).

**Comment by vctrainings08** [comment] 2023-05-31 17:23
Do we need both apigee.override.dealy and apigee.delay with proxy update options as override ?

**Comment by ssvaidyanathan** [comment] 2023-05-31 17:24
No - apigee.override.delay is enough

**Comment by vctrainings08** [comment] 2023-05-31 17:39
Okay but apigee.override.delay is already configured and still see message which in below exception,

throw new MojoExecutionException("Deployment failed: Bundle did not activate within expected time. Please check deployment status manually before trying again");

**Comment by ssvaidyanathan** [comment] 2023-05-31 17:42
Is this happening just for this deployment or for any proxy/sharedflow deployment?

**Comment by vctrainings08** [comment] 2023-05-31 17:43
It is happening for proxy/sharedflow everytime only on update with override.

**Comment by ssvaidyanathan** [comment] 2023-05-31 17:44
what do you mean by "update with override"? 
are you passing both update and override in the options?

**Comment by vctrainings08** [comment] 2023-05-31 17:45
I mean existing proxy deployment with options override.

**Comment by ssvaidyanathan** [comment] 2023-05-31 17:45
Can you share you mvn command and the profile config you are calling from Maven?

**Comment by vctrainings08** [comment] 2023-05-31 17:52
![image](https://github.com/apigee/apigee-deploy-maven-plugin/assets/121146311/f4eb10e9-63d1-4489-beef-e7b01397f5dc)

mvn command:
mvn install -Papigee -Dusername=**** -Dpassword=**** -Dorg=org_name -Denv=env_name -Dhosturl=apigee_ms_host -Doptions="override" -f <pomfile>

**Comment by ssvaidyanathan** [comment] 2023-05-31 17:54
Thank you. Can you confirm if its happening for all proxy deployments or just this one proxy?
I dont see anything wrong with the config or the command

**Comment by vctrainings08** [comment] 2023-05-31 17:56
It is happening intermittently for all the proxy/sharedflow deployments and issue is not coming post MS restart. Again after 3-4 days we're getting same issues.

**Comment by ssvaidyanathan** [comment] 2023-05-31 17:58
Anything in the logs? I am suspecting something is wrong with the services.

What happens when you try to deploy using the Management API directly? Does it work?

**Comment by vctrainings08** [comment] 2023-05-31 18:00
Yes Management API works well directly but it took around 30 secs to deploy where as deployment through plugin is failing with activation issue.

**Comment by ssvaidyanathan** [comment] 2023-05-31 18:25
Can you also share the logs from the mvn command?

**Comment by ssvaidyanathan** [comment] 2023-05-31 18:26
Also - can you remove the delay from the pom profile and try? Have you always had that set to 30?

**Comment by vctrainings08** [comment] 2023-06-01 16:16
I cannot provide logs. If I remove the delay then proxy traffic will be impacted correct. I set delay depends on environment and I usually set 10 during run time. Have you come across this issue and was it covered as part of your testing?

**Comment by ssvaidyanathan** [comment] 2023-06-01 16:19
@vctrainings08 - no I have not come across this. Not sure why the deployment is taking that long either. Shouldn't ideally but it could be possible that the delay you are providing is a reason why its failing. Can you try deploying the proxy using the Management API without the delay?

Do you get continuous traffic on the API which its being deployed?

**Comment by vctrainings08** [comment] 2023-06-02 13:26
As per apigee documentation delay is needed to handle deployment with zero down time. https://docs.apigee.com/api-platform/deploy/deploy-api-proxies-using-management-api

![image](https://github.com/apigee/apigee-deploy-maven-plugin/assets/121146311/350be054-ef54-4396-ba2d-abcb60609efb)

For deployment plugin, we have apigee.delay and apigee.override.dealy to enforce delay to handle traffic on existing traffic during deployments. Can I know which delay parameter will be passed to deployments API. 

Also may I know at which scenario below exception will be raised.

throw new MojoExecutionException("Deployment failed: Bundle did not activate within expected time. Please check deployment status manually before trying again");

Right now I see 10L is configured for Thread.sleep. Is delay value should be less than 10 seconds always?

**Comment by vctrainings08** [comment] 2023-06-03 06:48
Thank you for the response. Mvn log is attached below

![image](https://github.com/apigee/apigee-deploy-maven-plugin/assets/121146311/8ea55ad6-8d10-411e-9283-cc778fd93943)

**Comment by ssvaidyanathan** [comment] 2023-06-04 21:27
@vctrainings08 - Yes, the delay is included only to upload the bundle but not for checking the deployment. Not sure why your proxy is taking that long to deploy. How big is this bundle (zip)? Are other proxies also taking this much time?

Are you seeing this issue recently? If yes, what changed that this is occurring now?

The delay is needed only to do the deployment. The activation part is just checking if the deployment is complete and its state is set to "deployed". If thats taking too much time. I would want you to check why its taking this long. We have many many customers using this plugin and no one has reported this issue. So am wondering if your setup is really slow and thats causing this issue.

Its working for me on my end. I am using the public SaaS version.

**Comment by vctrainings08** [comment] 2023-06-05 05:39
Okay. Can we make the delay of 10sec which is hardcoded in plugin as parameter so that it won't be an issue even if MS takes more than 10 seconds to activate the bundle?

**Comment by ssvaidyanathan** [comment] 2023-06-05 15:12
@vctrainings08 - Can you pls respond to these questions
1) Did you try updating the override delay to something lower (say 10) and try? What happened?
2) Can you also try including `<apigee.delay>50</apigee.delay>` to your pom profile and see if that helps?

**Comment by ssvaidyanathan** [comment] 2023-08-18 17:32
Any other update? If the issue is not related to the plugin, can we close this?

**Comment by ssvaidyanathan** [comment] 2023-08-31 20:49
Closing due to inactivity

**Closed by ssvaidyanathan** 2023-08-31 20:49 UTC
