### ISSUE TITLE
config.json replacement code depends on <proxy>.xml/description to be present

### ISSUE THREAD

**Issue by seymen** [apigee/apigee-deploy-maven-plugin#73] opened 2017-03-23 11:19 UTC
it really shouldn't be as it is not a mandatory element.

Without config.json, maven can deploy a proxy without <description> but with config.json there, it fails with a "null" error message.

**Comment by ssvaidyanathan** [comment] 2017-03-23 21:39
@seymen - not able to reproduce. I can deploy proxies with no description and with a config.json

Can you share your bundle that is failing ?

**Comment by ssvaidyanathan** [comment] 2017-03-28 22:27
@seymen - is this resolved ?

**Comment by ssvaidyanathan** [comment] 2019-12-27 19:05
Closing this issue

**Closed by ssvaidyanathan** 2019-12-27 19:05 UTC
