### ISSUE TITLE
Deploy does not deploy all javascript resources

### ISSUE THREAD

**Issue by reffjitter** [apigee/apigee-deploy-maven-plugin#33] opened 2015-05-28 23:48 UTC
I am trying to deploy a proxy that has 12 jsc resources. All of the resources are accounted for in the proxy.xml. 

this is what I am seeing
[ERROR] 400 Bad Request
{
  "code" : "messaging.config.beans.InvalidResourceURLRef",
  "message" : "Invalid resource url ref jsc://js_memberInfoHash.js in policy js_hashMemberInfo in cambiahealth-nonprod",
  "contexts" : [ ],
  "cause" : {
    "code" : "messaging.config.beans.ResourceDoesNotExist",
    "message" : "Resource with name js_memberInfoHash.js and type jsc does not exist",
    "contexts" : [ ]
  }
}
I have check numerous times and the file is there. it will deploy via the gui.

This is the proxy giving me trouble
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Javascript async="false" continueOnError="false" enabled="true" timeLimit="200" name="js_hashMemberInfo">
    <DisplayName>js_hashMemberInfo</DisplayName>
    <ResourceURL>jsc://js_memberInfoHash.js</ResourceURL>
    <IncludeURL>jsc://js_MD5.js</IncludeURL>
</Javascript>

i notice that this policy has an includeURL, not sure if that is throwing off the count. 

Hoping this is a know issue with an easy work around, I don't want to had deploy these.

**Comment by aaronshaver** [comment] 2016-07-08 23:57
I'm having the exact same issue. I don't know what the fix is yet, but it's driving me nuts. Seems to be some kind of Maven or caching issue.

**Comment by ssvaidyanathan** [comment] 2016-07-11 17:02
Hi @aaronshaver - saw your post on the community. Will need some more info to debug

Which version of Maven are you using ?
I see you are trying the maven command on git bash shell on Windows. Can you try it on Windows Command prompt ? (not sure if that is the issue, try trial and error)
Can you also update your pom.xml to use the latest version (1.0.3) and use the -Doptions=update ?
This will not delete the proxy but update the existing revision (if that is what you need and don't want a lot of proxy revisions)

**Comment by aaronshaver** [comment] 2016-07-11 17:49
@ssvaidyanathan - thanks for the reply. Maven version is 3.3.1. That's the one my coworkers have as well.

When I try the Windows command prompt, it just opens Git Bash anyway and has the same error.

Ideally I could keep all my revisions, so I could go back. But I could probably live with replacing the current one. Give me a few minutes to try the pom.xml update and -Doptions

**Comment by aaronshaver** [comment] 2016-07-11 17:52
@ssvaidyanathan No change with pom version 1.0.3 - same error

**Comment by aaronshaver** [comment] 2016-07-11 17:54
@ssvaidyanathan No help with -Dapigee.options=update -- same error

**Comment by ssvaidyanathan** [comment] 2016-07-11 18:29
@aaronshaver - Thanks

Would it be possible to share the proxy bundle so that I can test it and see ? You can send it to me privately 

Are you trying this on Cloud or On Prem ?

**Comment by aaronshaver** [comment] 2016-07-11 18:33
Could you please email me at aaron.shaver@cambiahealth.com ?

**Comment by ssvaidyanathan** [comment] 2016-07-12 16:11
Hi

Looks like all the js files are not getting copied to the target folder. Since there are missing jsc files, when the bundle is being validated, it fails as the js files are part of the policy reference. Try adding this to your pom before calling the deploy plugin. 

```xml
<!-- copy the full apiproxy folder to target folder -->
<plugin>
	<artifactId>maven-resources-plugin</artifactId>
	<version>2.6</version>
	<executions>
		<execution>
			<id>copy-resources</id>
			<phase>package</phase>
			<goals>
				<goal>copy-resources</goal>
			</goals>
			<configuration>
				 <!--this is important -->
				<overwrite>true</overwrite>
				 <!--target -->
				<outputDirectory>${target.root.dir}/apiproxy</outputDirectory>
				<resources>
					<resource>
						 <!--source -->
						<directory>${project.root.dir}/apiproxy</directory>
					</resource>
				</resources>
			</configuration>
		</execution>
	</executions>
</plugin>

**Comment by aaronshaver** [comment] 2016-07-12 16:40
Thanks, Sai.

Note that while this works to solve the copying, it is breaking our inclusion of additional Apigee policies that come from a parent POM and a "common" proxy that's outside the current one. As such, this is only a partial solution. My ultimate solution will be to convert over to a Mac, because this issue is only happening on Windows computers.

**Comment by ericdahl-shutterfly** [comment] 2017-01-24 19:12
It's now 2017. Any chance this will be fixed? Is it expected that we instead add maven configuration to manually copy resource files?

**Comment by ericdahl** [comment] 2017-01-24 19:13
It's now 2017. Any chance this will be fixed? Is it expected that we instead add maven configuration to manually copy resource files?

**Comment by davidwallen** [comment] 2017-01-24 21:20
@ericdahl - can you also give us a view to the path to the file(s) that won't copy? I have seen similar issues with path lengths on Windows in the past. A test would be to move your project to the root of your drive and see if this clears up the issue.

**Comment by aaronshaver** [comment] 2017-01-24 21:23
@ericdahl - my team ended up finding a workaround where as long as you had an XML file that matched the extra .js resource, it would work. So if you have a new file Processor.js, you'd need to have a Processor.xml that referenced the .js file to make Apigee deploy happy.

**Comment by davidwallen** [comment] 2017-01-24 21:25
Interesting. Something for us to drill down on. Odd that this only occurs
on Windows - can you validate that point?

David Allen
m: 503-781-4045
w: www.allens-online.com  e: david@allens-online.com
<https://www.facebook.com/profile.php?id=100000547067793>
<https://twitter.com/davidwallen>   <https://www.linkedin.com/in/davidallen>

**Comment by ericdahl** [comment] 2017-01-26 00:41
> Hi @ericdahl - Can you share your proxy bundle with the pom file ? You can email it to me at ssvaidyanathan@google.com

Sorry, I was mistakenly thinking of https://github.com/apigee/proxy-dependency-maven-plugin/issues/23 -- that old issue from 2015 has caused issues for my team. I'm glad to see some activity on this repository, though the other is still dead.

**Comment by timothywmurray** [comment] 2017-05-18 21:19
Is there any resolution to this?

**Comment by ssvaidyanathan** [comment] 2017-05-18 21:22
HI @timothywmurray - which version are you using ? Can you confirm you are seeing the same issue that is js files not being copied ? Can you share your pom file ?

**Comment by timothywmurray** [comment] 2017-05-18 22:57
Hi Sai thanks for responding

Attached is the pom and parent pom
Today the issue is that XSLT files are not being copied
We are Apigee cloud (organization Cambiahealth)
As noted in the thread no solution was ever found last time

Thanks
Tim

**Comment by ssvaidyanathan** [comment] 2017-05-18 23:59
Hi @timothywmurray - I am not sure if the files are attached.
Would it be possible for you to send me the entire proxy zip including the poms ?
My email id is ssvaidyanathan@google.com

**Comment by timothywmurray** [comment] 2017-05-19 03:32
Hi again Sai,
I tried to email you directly at ssvaidyanathan@google.com but twice it
bounced as undeliverable.
My work email is timothy.murray@cambiahealth.com contact me and we can
either find a way to share the zip or do a screen share.
Tim

**Comment by ssvaidyanathan** [comment] 2017-05-19 20:19
Worked with @timothywmurray and got this fixed. Was not a plugin issue. The order of the plugins within the pom file matters. The copy-resources was called after the bundle is packaged. So the zip did not have the resources. With that change, it started to work. All good now !

@timothywmurray - I am closing this issue, if you still find any issues, please re-open this

**Closed by ssvaidyanathan** 2017-05-19 20:19 UTC
